### ISSUE TITLE
Handle unsupported python/ruby versions in a better way

### ISSUE THREAD

**Issue by david-gang** [grafana/pyroscope-rs#175]
**Describe the bug you encountered:**

Pyroscope-rs let's you install on unsupported python and ruby versions and then swallows the fact that it cannot upload the profiles silently

**What did you expect to happen instead?**
1. Document explicitely which python/ruby versions you support
2. Add these requirements in the python and ruby libraries so that it will throw an error in installation time
3. If you see that you cannot upload the profiles please write a warning

Look here for many bugs:

https://github.com/grafana/pyroscope-rs/issues/168
https://github.com/grafana/pyroscope-rs/issues/173
https://github.com/grafana/pyroscope-rs/issues/80

My use case is that the ruby sdk works in 3.1.4 but not in 3.1.5 and i get absolutely no error message. It is the same as https://github.com/grafana/pyroscope-rs/issues/173 If i would have get an error in the installation time i would have considered waiting with the upgrade to 3.1.5 .

...

**How did you install `pyroscope-rs`?**
with bundle

---

**pyroscope-rs version and environment**

**Comment by david-gang** [comment]
hi @grafana/pyroscope-rs I could take care of restricting pyroscope-rs for the python versions 3.7 to 3.11 and look how to do this in ruby. The question is if PRS are welcome. The repo looks a bit quiet in the last months.

**Comment by korniltsev** [comment]
We don't need restrictions for old versions. We need support for new versions.

**Comment by david-gang** [comment]
That's a valid point but there will be always a gap between when a new python version is released and this project supports this new version. The same goes for ruby. From my experience i installed python 3.12 and then got an error while using the sdk forcing me to use ebpf.
In ruby it was even more weird. My colleague upgraded the ruby version from 3.1.4 to 3.1.6 and i got no warning or error message. The profiles just disappeared silently. 
So the best would be to get a failure in the installation phase instead of getting the error anyway later
So either :
1. This project starts to support ruby and python versions while there are still in the rc phase.
2. They have in the requirements file (either gemfile or setup.py) which python versions they support.
3. You have a different dependency which supports newer versions of python/ ruby transparently
Of all options i would prefer 3 but i am not sure this is possible, afterwards 1. 
I agree the 2 is not great but it is better than the current situation.

WDYT?

**Comment by korniltsev** [comment]
I think we don't need restrictions for old versions. We need support for new versions.

**Comment by david-gang** [comment]
That's great. I am waiting for python 3.12 support but in 0.512 it is not supported.
There is nothing which hinders you to install pyroscope-rs on an unsupported version including python 3.12.
And the new release apparently won't support python >= 3.13


Regarding the limitation this is not my invention. Here are two high starred libraries which do the same thing.

https://github.com/robotframework/SeleniumLibrary/blob/master/setup.py#L44
https://github.com/tensorflow/privacy/blob/master/setup.py#L48

Anyway this is your project so if you disagree, then just close the issue. Just bear in mind that the current lack of support for newer python and ruby versions plus the fact that they don't fail in the installation phase cause lots of agony.

Thanks,
David

**Comment by korniltsev** [comment]
> cause lots of agony
I understand and agree.

**Comment by david-gang** [comment]
@korniltsev may you please share your plans how you are going to achieve support for new versions. This is especially hard in the case of pyroscope as there is no official api of the languages themselve. This is not like go which has pprof as part of its sdk

**Comment by korniltsev** [comment]
I don't know for sure

**Comment by korniltsev** [comment]
I am not going to work on this in the near future.
