### ISSUE TITLE
Release new pyroscope-rs version?

### ISSUE THREAD

**Issue by yanns** [grafana/pyroscope-rs#182]
There are main changes to `main` since the [0.5.7 release](https://github.com/grafana/pyroscope-rs/compare/lib-0.5.7...main), including https://github.com/grafana/pyroscope-rs/pull/140 that would avoid many transitive dependencies.

It'd be great if you could release a new version, thanks!

**Comment by mtralka** [comment]
Please see https://github.com/grafana/pyroscope-rs/pull/184 which aims to address CI issues so a release can be done:

Ref: https://github.com/grafana/pyroscope-rs/pull/181#issuecomment-2489076269

**Comment by korniltsev** [comment]
> There are main changes to main since the [0.5.7 release](https://github.com/grafana/pyroscope-rs/compare/lib-0.5.7...main)

Isnt 0.8.7 the latest? it still does  not support py312 though

**Comment by yanns** [comment]
You're speaking about the python package right?
My issue was about the rust SDK.

**Comment by korniltsev** [comment]
yep, I was talking about python. sorry for confusion. Rust was not updated even longer.

**Comment by YHM404** [comment]
any update?

**Comment by kushudai** [comment]
Could we also pull in https://github.com/grafana/pyroscope-rs/pull/188 for the next release please? 😄

**Comment by korniltsev** [comment]
published 0.5.8
