### ISSUE TITLE
Bump the clap from 3.x to 4.x

### ISSUE THREAD

**Issue by hi-rustin** [grafana/pyroscope-rs#92]
Clap was released for a while. I think maybe it would be nice to upgrade the clap from 3.x to 4.x for the pyroscope CLI.

If you think it makes sense I can help to add UI tests for CLI and bump the clap version.

**Comment by korniltsev** [comment]
Does it require to update rust toolchain? I would like to keep 1.63 for as long as possible because 1.64 bumps glibc dependency, preventing running pyroscope-rs on ridiculously old systems for no good reason for pyroscope. If it does not require to update toolchain - I am open to upgrade
