### ISSUE TITLE
Missing binaries in pyroscope-cli releases. 

### ISSUE THREAD

**Issue by AlexBoyd** [grafana/pyroscope-rs#96]
**Describe the bug you encountered:**

The docs suggest that binaries of the pyroscope-cli should be available under releases, but the tagged releases in github only provide the source code at the moment. 

Docs: (https://github.com/pyroscope-io/pyroscope-rs/tree/main/pyroscope_cli#installation) 
Example release: (https://github.com/pyroscope-io/pyroscope-rs/releases/tag/cli-0.2.1)

Looking at the actions definition, the release process for the cli does build the crate and publish that, but doesn't upload the binary to the releases page as far as I can tell. (https://github.com/pyroscope-io/pyroscope-rs/blob/main/.github/workflows/publish.yml#L26)

...

**What did you expect to happen instead?**

Binaries available on the releases page, for easy installation into environments without the full rust tool chain setup. 
...

**Comment by korniltsev** [comment]
I've fixed building and publishing to github release and dockerhub, but not crates yet.
https://github.com/grafana/pyroscope-rs/releases/tag/cli-0.2.7
